server.port=8080
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Localizador automático de respaldo
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# 1. Usuarios
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# 2. Canchas
spring.cloud.gateway.routes[1].id=ms-canchas
spring.cloud.gateway.routes[1].uri=lb://ms-canchas
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/canchas/**

# 3. Autenticación
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

# 4. Admin / Seguridad
spring.cloud.gateway.routes[3].id=security-service
spring.cloud.gateway.routes[3].uri=lb://security-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/admin/**

# 5. Reservas
spring.cloud.gateway.routes[4].id=ms-reservas
spring.cloud.gateway.routes[4].uri=lb://ms-reservas
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/reservas/**

# 6. Pagos
spring.cloud.gateway.routes[5].id=ms-pagos
spring.cloud.gateway.routes[5].uri=lb://ms-pagos
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/pagos/**

# 7. Disponibilidad
spring.cloud.gateway.routes[6].id=ms-disponibilidad
spring.cloud.gateway.routes[6].uri=lb://ms-disponibilidad
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/disponibilidad/**

# 8. Notificaciones
spring.cloud.gateway.routes[7].id=ms-notificaciones
spring.cloud.gateway.routes[7].uri=lb://ms-notificaciones
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notificaciones/**

# 9. Calificaciones
spring.cloud.gateway.routes[8].id=ms-calificaciones
spring.cloud.gateway.routes[8].uri=lb://ms-calificaciones
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/calificaciones/**

# 10. Reportes
spring.cloud.gateway.routes[9].id=ms-reportes
spring.cloud.gateway.routes[9].uri=lb://ms-reportes
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/reportes/**